### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by JPchico**
Bump version number to 1.0.0

Updating the Changelog.

Removing the documentation under development banner.

### CODE REVIEW

**Comment by JPchico** [comment]
@chrisjsewell , @sphuber any comments before merging this?
I assume that I can make the tag and release directly from the release github tab right?

**Review by sphuber — APPROVED** [review]
Thanks for all the work @JPchico . Great to see this milestone!

> I assume that I can make the tag and release directly from the release github tab right?

Not sure what you mean with this. What I would do is the following. After you merge the PR, do the following in your local clone:
```
git fetch --all
git checkout develop
git pull origin develop
git tag v1.0.0
git push --tags
```
Essentially you create the tag on the latest commit on `develop` and push it.

**Comment by chrisjsewell** [comment]
All looks good cheers 🎉 
You need to merge develop in to master before releasing.
You just make the release from GitHub and it creates the tag for you.

Then we can delete develop/development branches and work straight from master.

**Comment by chrisjsewell** [comment]
> After you merge the PR, do the following in your local clone ...

Nope 👎 😉 just do it from GitHub

**Comment by JPchico** [comment]
Thank you for your help @chrisjsewell  and @sphuber ! The release is done! If something comes up just let me know!

**Pull request merged**
