### PR TITLE
Add MACE potential

### PR DESCRIPTION
**Pull request by mankoNm**
Add the possibility to work with binary potentials.

### CODE REVIEW

**Review by JPchico — COMMENTED** [review]
@mankoNm This looks good!
One question, do you think it would be possible to add a test?
Another thing, I see that the documentation is failing, does the same happen when you try running the pipeline locally?

**Comment by mankoNm** [comment]
> @mankoNm This looks good!
> One question, do you think it would be possible to add a test?
> Another thing, I see that the documentation is failing, does the same happen when you try running the pipeline locally?

I have encountered the same issues with the documentation failing when running the pipeline locally. Unfortunately, I am not very familiar with the documentation setup and am having trouble identifying the cause of these failures.

Regarding the tests, I believe adding a test might not be necessary at this point because my changes are mainly aimed at ensuring the code can handle potentials in binary format. I have not altered any logic that would require new tests at this time.

If you have any specific suggestions or guidance on troubleshooting the documentation errors, I would greatly appreciate it.

**Comment by JPchico** [comment]
@mankoNm Sorry for the late reply I was on holidays.

I think I know why the documentation is failing and I should be able to fix it, I think it is a setting in which warnings are causing the build to fail. I will make a PR to fix it.

> Regarding the tests, I believe adding a test might not be necessary at this point because my changes are mainly aimed at ensuring the code can handle potentials in binary format. I have not altered any logic that would require new tests at this time.

Fair enough, it everything works I think that is good.


I'll make the PR to fix the documentation and then merge your PR if that is okay. I will try to do it today.

**Comment by mankoNm** [comment]
> @mankoNm Sorry for the late reply I was on holidays.
> 
> I think I know why the documentation is failing and I should be able to fix it, I think it is a setting in which warnings are causing the build to fail. I will make a PR to fix it.
> 
> > Regarding the tests, I believe adding a test might not be necessary at this point because my changes are mainly aimed at ensuring the code can handle potentials in binary format. I have not altered any logic that would require new tests at this time.
> 
> Fair enough, it everything works I think that is good.
> 
> I'll make the PR to fix the documentation and then merge your PR if that is okay. I will try to do it today.

Dear @JPchico 

Sorry for the late reply I also was on holidays :)
For me it sounds good. 


It sonds good for me. I

**Review by JPchico — APPROVED** [review]
Hello @mankoNm sorry for the long delay again, it was a kinda crazy week. I have fixed the problem with the documentation as you see so all tests are passing.

I noticed that you also added the atom_modify command, this is quite nice. I will approve as it is now, and if you have other features that you want to add please feel free to make other PRs.

**Pull request merged**
