### PR TITLE
Adding check for the raw calculation to see if lammps has exited with an error

### PR DESCRIPTION
**Pull request by JPchico**
Adding check for the raw calculation to see if lammps has exited with an error. Addresses #87

### CODE REVIEW

**Review by sphuber — COMMENTED** [review]
Changes look good, thanks @JPchico . Would be great if you could add a quick test. Does one already exist for the other parser?

**Comment by JPchico** [comment]
Hi @sphuber! No there is no test for this, so I'll add one for both parsers.

**Comment by JPchico** [comment]
@sphuber tests added. If you agree I'll merge this one.

**Review by sphuber — APPROVED** [review]
Thanks @JPchico good to go

**Pull request merged**
