### PR TITLE
Fixing an issue in which the arrays names

### LINKED ISSUE #42: Change name of Arrays that does not conform to AiiDA naming convention
The names generated by lammps, might result in array names that are not suitable for aiida. Hence one needs to change the names of the arrays so that they can be stored in the database without problem.

This tends to happen when one is trying to store arrays that have `[` in the name.

### PR DESCRIPTION
**Pull request by JPchico**
Fixing an issue in which the arrays names might not be compatible with what AiiDA enforces. For that the `[` and `]` that are usually given by lammps to arrays components are replaces by `__`. Fixes #42.

### CODE REVIEW

**Comment by JPchico** [comment]
I realized that his had somehow gotten pass me. I wonder how it was working before since it seems to be that the name enforcement is quite old. 

I notice that the docs are being built always, is that intended @chrisjsewell ?

**Comment by chrisjsewell** [comment]
Heya, If you update your branch, #45 should fix the docs

**Comment by JPchico** [comment]
Great! It should be fixed now (after some struggling with the reference names). I also changed it so that the trajectories and other outputs follow the same conventions and using the regex as we discussed.

**Review by chrisjsewell — APPROVED** [review]
Cheers!

**Pull request merged**
